/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutDialog: typeof import('./src/components/AboutDialog.vue')['default']
    CodeView: typeof import('./src/components/CodeView.vue')['default']
    ExamplesBox: typeof import('./src/components/ExamplesBox.vue')['default']
    GlobalSnackbar: typeof import('./src/components/GlobalSnackbar.vue')['default']
    MarkedView: typeof import('./src/components/MarkedView.vue')['default']
    MinDfaTab: typeof import('./src/components/MinDfaTab.vue')['default']
    NfaToDfaTab: typeof import('./src/components/NfaToDfaTab.vue')['default']
    RegexToNfaTab: typeof import('./src/components/RegexToNfaTab.vue')['default']
    SettingsView: typeof import('./src/components/SettingsView.vue')['default']
    ShowDfaTab: typeof import('./src/components/ShowDfaTab.vue')['default']
    ShowNfaTab: typeof import('./src/components/ShowNfaTab.vue')['default']
    ViewMapView: typeof import('./src/components/ViewMapView.vue')['default']
  }
}
